[book]
authors = ["0xMRTT"]
language = "en"
multilingual = false
src = "src"
title = "CRS, a simple project generator."

[rust]
edition = "2021" 

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/0xMRTT/crs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/0xMRTT/crs/edit/master/docs/{path}"
input-404 = "not-found.md"