name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.BOT_ACCESS_TOKEN }}
          issue-message: "<h3>Thank you for your feedback on this project! </h3> We will endeavour to get back to you soon."
          pr-message: "<h3>Thank you for contributing to this project! </h3> Your support is much appreciated. We will endeavour to get back to you soon."
