name: Label Commenter

on:
  issues:
    types: [labeled, unlabeled, opened]
  pull_request_target:
    types: [labeled, unlabeled, opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
